services:
    backend:
        container_name: backend
        build:
            context: ./packages/backend
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
            - SRC_PATH=${SRC_PATH}
            - TRG_PATH=${TRG_PATH}
        ports:
            - '3001:3001'
        volumes:
            - SRC_PATH:/data/src
            - TRG_PATH:/data/trg
            - ./packages/backend/prisma:/app/prisma
            # - sqlite-data:/app/prisma/dev.db
        restart: unless-stopped

    frontend:
        container_name: frontend
        build:
            context: ./packages/frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
        depends_on:
            - backend
        restart: unless-stopped
